samples:
  - 8A-D2-SS-root
  - 8B-D2-SS-root

# Mandatory options for the WGS Pipeline. 
input_dir: /mnt/ngs/projects/wgs_pipeline_testing_6180/users/vbn649/WGS_Trace/20240413_WGS_Hair/20240318_WGShair_second_analysis/
output_dir: /mnt/ngs/projects/wgs_pipeline_testing_6180/users/vbn649/WGS_Trace/20240413_WGS_Hair/20240318_WGShair_second_analysis/analysis/

# Additional options for the WGS Pipeline (leave empty if not used). For explanation of every option run: biss_bwa_pipeline_v1.4_rocky -h
threads: ""            # e.g., 24
reference: ""          # e.g., ref/hg38.fa
base: ""               # e.g., sample1
gatk: ""               # e.g., path/to/gatk.jar
adapter1: ""           # e.g., AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adapter2: ""           # e.g., AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
trim_q: ""             # e.g., 20
trim_l: ""             # e.g., 30
trim_n: ""             # e.g., 3
n_aln: ""              # e.g., 2
snps: ""               # e.g., path/to/snps.vcf

# Boolean flags for pipeline behavior
rdupli: false
bwa_aln: false
fastq: false
force: false
pcr: false
debug: false
no_collapse: false


################################################################################################
########################################## SECONDARY ###########################################
########################################## ANALYSES ############################################
################################################################################################


# Set the tools you want to run to true (remember to check the other options!):
get_empop_input: true
mt_cov_threshold: 100

run_yleaf: true
reads_treshold: 8

extract_AIMs: true

# YOU NEED TO SPECIFY THE "ini" PATH TO RUN THE ANALYSIS CORRECTLY!
extract_STRs: true
ini_file: /mnt/ngs/projects/wgs_pipeline_testing_6180/users/wmj412/testing/Global_filer_hg38.ini

sex_determination_skoglund: true
sex_determination_anastasiadou: true



########################################## IMPORTANT! ###########################################
# mapDamage Can ONLY run on ngs01 for now. To be able to run it you have to change your .bashrc accordingly:
#First open a terminal on one of the linux servers.

#Then make a backup of your old .bashrc (there is a space before each ~):
# mv ~/.bashrc ~/.bashrc_old

# Then copy the new one instead (two spaces in all):
# cp /mnt/ngs/biss/opt/recommended_configs/.bashrc ~/.bashrc

#Close the terminal and open a new terminal to activate the bashrc.

run_mapdamage: true



################################################################################################
###################################### WORK IN PROGRESS: #######################################
################################################################################################
######################################### DO NOT RUN! ##########################################
################################################################################################


# I did not manage to finish setting up the R code for HIrisPlex-S extraction to run in Snakemake
# It is however possible to run it manually on your own and can be found here:
# /mnt/ngs/projects/wgs_pipeline_testing_6180/users/wmj412/20250523_summary_script_pipeline/Assign_Genotypes_HIrisplexS
# Aleks
extract_HIrisPlexS: true

# This rule is not been properly set up!
library_complexity_picard: false

# Preseq is not installed globaly on the server!
library_complexity_preseq: false

# Custom library complexity have not been proprerly set up!
library_complexity_custom: false


# Demixtify is not installed globaly on the server!
run_demixtify: false

################################################################################################
###################################### END OF THE CONFIG #######################################
################################################################################################
