samples:
  - 8A-D2-SS-root
  - 8B-D2-SS-root

# The analysis directory where all the output directories from the biss_WGS_pipeline can be found: 
output_dir: /mnt/ngs/projects/wgs_pipeline_testing_6180/users/wmj412/testing/analysis/

# Set the tools you want to run to true (remember to check the other options!):
get_empop_input: true
mt_cov_threshold: 100

run_yleaf: true
reads_treshold: 8

extract_AIMs: true

# YOU NEED TO SPECIFY THE "ini" PATH TO RUN THE ANALYSIS CORRECTLY!
extract_STRs: true
ini_file: /mnt/ngs/projects/wgs_pipeline_testing_6180/users/wmj412/testing/Global_filer_hg38.ini

sex_determination_skoglund: true
sex_determination_anastasiadou: true



########################################## IMPORTANT! ###########################################
# mapDamage Can ONLY run on ngs01 for now. To be able to run it you have to change your .bashrc accordingly:
#First open a terminal on one of the linux servers.

#Then make a backup of your old .bashrc (there is a space before each ~):
# mv ~/.bashrc ~/.bashrc_old

# Then copy the new one instead (two spaces in all):
# cp /mnt/ngs/biss/opt/recommended_configs/.bashrc ~/.bashrc

#Close the terminal and open a new terminal to activate the bashrc.

run_mapdamage: true



################################################################################################
###################################### WORK IN PROGRESS: #######################################
################################################################################################
######################################### DO NOT RUN! ##########################################
################################################################################################

# I did not manage to finish setting up the R code for HIrisPlex-S extraction to run in Snakemake
# It is however possible to run it manually on your own and can be found here:
# /mnt/ngs/projects/wgs_pipeline_testing_6180/users/wmj412/20250523_summary_script_pipeline/Assign_Genotypes_HIrisplexS
# Aleks
extract_HIrisPlexS: true

# This rule is not been properly set up!
library_complexity_picard: false

# Preseq is not installed globaly on the server!
library_complexity_preseq: false

# Custom library complexity have not been proprerly set up!
library_complexity_custom: false


# Demixtify is not installed globaly on the server!
run_demixtify: false

################################################################################################
###################################### END OF THE CONFIG #######################################
################################################################################################
